name = "HermiteUtils"
uuid = "f45b5e90-996a-4e4c-8893-32c2a001dee8"
authors = ["Jack Coughlin <jack@johnbcoughlin.com> and contributors"]
version = "0.1.0"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
FastGaussQuadrature = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
